#frontend-deployment.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: song-lister-frontend
        image: wwilliam02/song_lister_frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: backend_url



---
# backend-deployment.yaml

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: song-lister-backend
        image: wwilliam02/song_lister_backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: mongo_uri

# frontend-configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    data: config
data:
  # Add environment variables here for frontend
  backend_url: http://backend-svc:8080
---
# backend-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels: 
    data: config
data:
  # Add environment variables here for backend
  mongo_uri: mongodb://mongodb:27017
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb
 labels:
  app: mongodb
spec:
 ports:
  - port: 27017
    targetPort: mongodb-port
 selector:
  app: mongodb
---
# mongo-deployment-yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb-port
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /data/configdb
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
  - metadata:
      name: mongo-config
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Mi
